cassandra 4.x migration guide
vert-x3/vertx-4-migration-guide pull request #17
Opened 2020-09-03 10:02 UTC by Sammers21

Closes #7

2020-09-04 09:03 UTC, tsegismont requested changes
Thanks @Sammers21 !

2020-09-04 09:03 UTC, tsegismont commented on asciidoc/cassandra.adoc
> +is incompatible the previous one. Migration process might involve import changes and
```suggestion
is incompatible with the previous one. Migration process might involve import changes and 
```

2020-09-04 09:03 UTC, tsegismont commented on asciidoc/cassandra.adoc
> +In Vert.x 4 Cassandra Client uses a new major 4.x version of Datastax Java driver, which
```suggestion
In Vert.x 4 Cassandra Client uses the latest major version of Datastax Java driver (4.x), which
```

2020-09-04 09:03 UTC, tsegismont commented on asciidoc/cassandra.adoc
> +==== CassandraClientOptions changes
```suggestion
==== `CassandraClientOptions` changes
```

2020-09-04 09:03 UTC, tsegismont commented on asciidoc/cassandra.adoc
> +Construction of CassandraClientOptions now might require different imports:
```suggestion
Construction of `CassandraClientOptions` now might require different imports:
```

2020-09-04 09:03 UTC, tsegismont commented on asciidoc/cassandra.adoc
> +`addContactPoint` is expected to be used.
Can you add examples for Vert.x 3 and 4 like you did above?

2020-09-07 13:40 UTC, Sammers21 commented
@tsegismont, can you review the PR once again, please?

2020-09-08 07:48 UTC, tsegismont approved these changes
Thank you @Sammers21 !

2020-09-08 07:48 UTC, merged